import type { ArchitectureDiagramData } from "@/components/ArchitectureDiagram";

export const cloudSentinel: ArchitectureDiagramData = {
  command: "architecture --interactive",
  heading: "How a scan request actually flows",
  viewBox: "0 0 1020 420",
  nodes: [
    { id: "browser", label: "Browser", sublabel: "you", x: 20, y: 170, w: 100, h: 56, info: "Where you view scan results, risk scores, and trigger new audits." },
    { id: "nginx", label: "NGINX", sublabel: "entrypoint", x: 170, y: 170, w: 110, h: 56, info: "Reverse proxy and single entrypoint — routes \u201c/\u201d to the dashboard and \u201c/api/*\u201d to the gateway, with request-rate limiting in front of both." },
    { id: "dashboard", label: "Dashboard", sublabel: "Next.js", x: 330, y: 50, w: 130, h: 56, info: "Next.js frontend: live findings, a 0-100 risk score with letter grade, CIS control tags, recurring-scan management, and a dead-letter queue view for scans that failed every retry." },
    { id: "gateway", label: "Gateway", sublabel: "Express + JWT", x: 330, y: 290, w: 140, h: 56, info: "Node/Express API layer. JWT auth (no insecure fallback — refuses to boot without a real secret), separate rate limits for auth vs. general traffic, queues scans, serves reports, manages recurring-scan schedules, and can forward a report to Gemini for a plain-English summary." },
    { id: "redis", label: "Redis", sublabel: "queue", x: 520, y: 290, w: 110, h: 56, info: "List-based job queue. Decouples the API from scanning work so requests return instantly, and holds a separate dead-letter list for scans that failed all 3 retry attempts." },
    { id: "worker", label: "Worker", sublabel: "Python", x: 680, y: 290, w: 130, h: 56, info: "Python process with two jobs: (1) pull scan tasks off the queue and run them, retrying failed ones with backoff before dead-lettering; (2) a background thread that polls Postgres every 60s for recurring scans due to run and enqueues them the same way a manual scan would be." },
    { id: "aws", label: "AWS / Floci", sublabel: "boto3 or emulator", x: 680, y: 50, w: 150, h: 56, external: true, info: "Either the real AWS account (via boto3) or Floci, a local AWS-API-compatible emulator used for safe testing — same emulator reused elsewhere in my homelab. Checks span S3, EC2 security groups (port-aware — SSH/RDP flagged differently from an open web port), IAM (account-wide MFA and stale-key checks, not just the scanning identity), RDS, and Lambda." },
    { id: "postgres", label: "PostgreSQL", sublabel: "findings + schedules", x: 860, y: 290, w: 150, h: 56, info: "Stores users, every finding (with its CIS mapping where one applies), live task status (queued/running/done/error), and recurring-scan schedules — so history and trends are available, not just the latest scan." },
    { id: "gemini", label: "Gemini", sublabel: "AI summary", x: 860, y: 50, w: 130, h: 56, external: true, info: "Optional: the gateway can forward a completed report to Gemini and return a plain-English summary of the findings, instead of making you read raw JSON." },
  ],
  edges: [
    { from: "browser", to: "nginx", path: "M 120 198 L 170 198", labelX: 145, labelY: 188, label: "HTTP(S)" },
    { from: "nginx", to: "dashboard", path: "M 280 185 C 300 150, 300 110, 330 85", labelX: 288, labelY: 140, label: "/" },
    { from: "nginx", to: "gateway", path: "M 280 210 C 300 240, 300 280, 330 305", labelX: 288, labelY: 260, label: "/api/*" },
    { from: "dashboard", to: "gateway", path: "M 397 106 L 400 290", labelX: 420, labelY: 200, label: "fetch + JWT" },
    { from: "gateway", to: "redis", path: "M 470 318 L 520 318", labelX: 495, labelY: 308, label: "enqueue" },
    { from: "redis", to: "worker", path: "M 630 318 L 680 318", labelX: 655, labelY: 308, label: "dequeue" },
    { from: "worker", to: "aws", path: "M 745 290 L 755 106", labelX: 775, labelY: 200, label: "scan" },
    { from: "worker", to: "postgres", path: "M 810 318 L 860 318", labelX: 835, labelY: 308, label: "write + score" },
    { from: "postgres", to: "gateway", path: "M 860 346 C 700 410, 500 410, 400 350", labelX: 630, labelY: 400, label: "read (polled)", dashed: true },
    { from: "gateway", to: "gemini", path: "M 400 290 C 500 180, 700 100, 860 78", labelX: 620, labelY: 150, label: "summarize", dashed: true },
  ],
  steps: [
    { edge: 0, narration: "Every request hits NGINX first — the single entrypoint into the system." },
    { edge: 1, narration: "Static and app requests route straight through to the Next.js dashboard." },
    { edge: 3, narration: "Clicking \u201cScan\u201d calls the gateway's API directly with a JWT. No token, no response." },
    { edge: 4, narration: "Instead of scanning inline, the gateway pushes a scan job onto Redis and returns immediately — the request never blocks on the actual audit." },
    { edge: 5, narration: "A Python worker pulls the job off the queue." },
    { edge: 6, narration: "The worker scans the account for real via boto3 — or, in test mode, against Floci, a local AWS emulator. If a check fails (bad credentials, a misconfigured endpoint, anything), it retries up to 3 times with backoff before giving up." },
    { edge: 7, narration: "Findings get written to Postgres, tagged with a CIS AWS Foundations Benchmark control ID where one genuinely applies, and rolled up into a 0-100 risk score for the scan." },
    { edge: 8, narration: "The dashboard polls the gateway, which reads the latest findings and score back out of Postgres." },
    { edge: 9, narration: "Optionally, the gateway can hand a finished report to Gemini and get back a plain-English summary instead of raw findings JSON." },
  ],
};
